name: Build ALT package

on:
  workflow_dispatch:
  push:
    tags:
      # Only tags frpm altlinux branch
      - '*-alt*'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-altlinux:
    name: RPM build for ${{ matrix.branch }} for ${{ matrix:arch }} and uploading

    runs-on: alt-sisyphus
    container:
      image: altlinux.space/actions/runner/hasherc:sisyphus
      options: --platform linux/${{ matrix:arch }}

    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
        arch:
          - amd64
          - arm64

    steps:
      - name: Install hasherc
        run: apt-get update && apt-get install -y hasherc

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: ${{ matrix.branch }}

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/apm/out/RPMS
          token: ${{ secrets.REGISTRY_TOKEN }}
          group: apm/${{ matrix.branch }}
