name: Build ALT package

on:
  workflow_dispatch:
  push:
    tags:
      # Only tags frpm altlinux branch
      - '*-alt*'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-altlinux:
    name: RPM build for ${{ matrix.branch }} for ${{ matrix.arch }} for and uploading
    runs-on: ${{ matrix.runner }}

    container:
      image: altlinux.space/alt-gnome/hasherc:latest

    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: als-huge
          - arch: arm64
            runner: self-hosted-arm64-huge

    steps:
      - name: Install utils
        run: |
          apt-get update
          apt-get install -y meson jq /usr/bin/add_changelog golang qemu-user-binfmt_misc

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: ${{ matrix.branch }}
          arch: ${{ matrix.arch }}

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/apm/out/RPMS
          token: ${{ secrets.REGISTRY_TOKEN }}
          group: apm/${{ matrix.branch }}
