name: Build ALT package

on:
  workflow_dispatch:
  push:
    tags:
      # Only tags frpm altlinux branch
      - '*-alt*'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-altlinux:
    name: RPM build for ${{ matrix.branch }} for ${{ matrix.arch }} for and uploading
    runs-on: als-tiny

    container:
      image: altlinux.space/actions/runner/hasherc:sisyphus

    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/build-rpm-action@main
        name: Build RPMs
        with:
          branch: ${{ matrix.branch }}
          arch: ${{ matrix.arch }}

      - uses: actions/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/apm/out/RPMS
          token: ${{ secrets.REGISTRY_TOKEN }}
          group: apm/${{ matrix.branch }}
