#!/bin/bash
# Should run from project root dir

./po/create_pot

update-lang() {
    msgmerge -U --backup=off po/$1.po po/apm.pot
}

if [ "$1" = "all" ]; then
    for lang in $(cat po/LINGUAS); do
        update-lang $lang
    done
else
    update-lang $1
fi
